### ISSUE TITLE
Add information on Google Sign In

### ISSUE THREAD

**Issue by ForceGT** [SmoothMaverick/SwiftUIFirebaseAuthDemo#1]
Can you show how Google sign in can be done?

**Comment by SmoothMaverick** [comment]
The README.md includes a link on how to setup the project in Firebase:

https://firebase.google.com/docs/ios/setup

But I don't mind adding some more details to be explicit.

**Comment by SmoothMaverick** [comment]
Sorry, I misread your issue.

Yes, I can include some example code to implement Google Sign-in.

**Comment by SmoothMaverick** [comment]
@ForceGT I added this commit:
https://github.com/SmoothMaverick/SwiftUIFirebaseAuthDemo/commit/395b771e997cd136714ad165b855fe2088f691b7

Now there is are Google Sign In buttons. Just need to add your Google plist file and add the URL scheme to your XCode project.

**Comment by SmoothMaverick** [comment]
Closing this issue for the time being. Please re-open if this needs more work.
